### PR TITLE
migrate Plugin and Demo to NativeScript 7

### PR DESCRIPTION
**Pull request by felixkrautschuk**
I migrated the plugin code and demo app to NS 7 and was able to test it on Android. I'm not able to test it on iOS right now because I still need to use Xcode 11 for some projects. But I mostly fixed the imports only for NS 7, so if it runs correctly on Android, it should work for iOS as well.

### CODE REVIEW

**Comment by jibon57** [comment]
@felixkrautschuk thanks for your contribution. I've sent you a request to be a maintainer of this project. I'm no longer using NativeScript now. Can I get your npm username please?

**Comment by felixkrautschuk** [comment]
@jibon57 my npm username is felixkrautschuk
but I need to mention that I have no experiences with npm or releasing/publishing/updating plugins :)

**Comment by Sauvetonbio** [comment]
Hello @felixkrautschuk , thank's for your work, we are interested to use this plugin with NS 7. How can we do if this update is not released ? Thank you again 👍

**Comment by felixkrautschuk** [comment]
@Sauvetonbio v. 3.0.0 is published. I need to mention that I was not able to test the NS 7 changes on iOS, because I still need to use XCode 11.7 for some NS 6 projects.
So if you are already using NS 7 and have Xcode 12 installed, feel free to test it and to give feedback here.

**Comment by Sauvetonbio** [comment]
@felixkrautschuk Thank's for publishing it ! For now it results errors with NS 7 and Xcode 12.
` import { Braintree, BrainTreeOptions } from 'nativescript-braintree';
let braintree = new Braintree();`

Result :

`***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Class constructor Observable cannot be invoked without 'new'
at
Braintree(file: node_modules/nativescript-braintree/braintree.ios.js:13:27)
at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./components/main/home.vue?vue&type=script&lang=js&(file: app/components/main/home.vue:50:0)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file: app/webpack/bootstrap:120:0)
at ./components/main/home.vue?vue&type=script&lang=js&(file: app/components/main/home.vue?2059:1:0)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file: app/webpack/bootstrap:120:0)
at ./components/main/home.vue(file: app/components/main/home.vue:1:0)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file: app/webpack/bootstrap:120:0)
at ../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js?!./frames/main.vue?vue&type=script&lang=js&(file:///app/bundle.js:7303:79)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file:///app/runtime.j<\M-b\M^@\M-&>
`

**Comment by felixkrautschuk** [comment]
@Sauvetonbio I see that you are building your app with Vue, unfortunately I have no experience with Vue.js.
Could you please try to run the demo app from this repo first, does the same error message occur there? ("Class constructor Observable cannot be invoked without 'new' at Braintree")

**Comment by Sauvetonbio** [comment]
Hello @felixkrautschuk ,
Just tried your demo. Got exactly the same issue.

`***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Class constructor Observable cannot be invoked without 'new'
at
Braintree(file: node_modules/nativescript-braintree/braintree.ios.js:13:0)
at brainTreePayment(file: app/main-view-model.ts:32:24)
at _handleEvent(file: node_modules/@nativescript/core/data/observable/index.js:228:0)
at notify(file: node_modules/@nativescript/core/data/observable/index.js:214:0)
at _emit(file: node_modules/@nativescript/core/data/observable/index.js:254:0)
at push.../node_modules/@nativescript/core/ui/button/index.js.TapHandlerImpl.tap(file: node_modules/@nativescript/core/ui/button/index.ios.js:254:0)
`

**Comment by bastienlemaitre** [comment]
Same error on Android with Nativescript Angular
package.json:
```
{
  "name": "@nativescript/template-hello-world-ng",
  "main": "main.js",
  "version": "7.0.8",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~3.0.0",
    "nativescript-braintree": "^3.0.0",
    "nativescript-oauth2": "^3.0.2",
    "nativescript-secure-storage": "^2.6.2",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~11.0.0",
    "typescript": "~4.0.0"
  },
  "gitHead": "41a7254d3bc134fd3c258761f3c6e1c3d54e6d41",
  "private": "true",
  "readme": "NativeScript Application"
}
```

Error:
```
ERROR TypeError: Class constructor Observable cannot be invoked without 'new'
```

**Comment by bastienlemaitre** [comment]
@jibon57  ?

**Comment by Sauvetonbio** [comment]
Hello @jibon57, I tried your tsconfig.json fix. I got this error :
`***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
../node_modules/nativescript-braintree/braintree.js(file: node_modules/nativescript-braintree/braintree.ios.js:202:4)
`

I removed manually NativeClass in the file, and got the plugin working like a charm on iOS :)
Thank you.

**Comment by felixkrautschuk** [comment]
@Sauvetonbio I did the fix as according to the docs, one should add this NativeClass decorator.
Unfortunately I am still not able to install Xcode 12 yet to test everything on ios.

But if you say you are able to use the plugin right now, then my previous commit (tsconfig compileOptions "target": "es2017",...) fixed your app from crashing.

For now, I will undo my commit regarding the @NativeClass decorator and will release version **3.0.1** as soon as possible.

**Comment by jibon57** [comment]
@felixkrautschuk I think correct decorator will be `@NativeClass()`. I quick read from [here](https://nativescript.org/blog/nativescript-7-for-plugin-authors/).

**Comment by felixkrautschuk** [comment]
@jibon57 thanks for that hint. Maybe @Sauvetonbio could temporary add the @NativeClass() again and check if it works, then I would publish that. Still wondering why it seems to work totally without that decorator...

**Comment by Sauvetonbio** [comment]
Hello, when adding @NativeClass() I get this :
`***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
../node_modules/nativescript-braintree/braintree.js(file: node_modules/nativescript-braintree/braintree.ios.js:201:0)`

Also, by removing NativeClass decoaror, the events (success, cancel...) are not working. I did'nt check that last time.

**Comment by felixkrautschuk** [comment]
@Sauvetonbio I gave another try to the NativeClass decorator in the **3.0.2** release. It should be available soon.

**Comment by felixkrautschuk** [comment]
@Sauvetonbio @bastienlemaitre are you able to build your app for **iOS** using this braintree plugin properly?
I ask you because I am not able to build the demo app of this repo and I am also not able to build a newly created app for iOS after installing this plugin.

I get the same error message described in a thread of the nativescript-community/ui-mapbox plugin:
https://github.com/nativescript-community/ui-mapbox/issues/3#issuecomment-732140591

My config is:
- NativeScript CLI: 7.0.11
- XCode: 12.2 (12B45b)

I have absolutely no idea why I am not able to build the ios app project. I also made a private plugin for NativeScript Braintree where I do some special stuff that I can not share here, but it has pretty much the same setup of this plugin, so I mean the same NativeScript module versions, webpack version and even the same versions of the iOS Braintree Pod dependencies.
And when I create a new app using that private plugin, the build works fine as expected.

So I am wondering why you are able to build your apps using this public plugin (otherwise you would not have seen the NativeClass error messages before). Can you please share your NativeScript and XCode configuration?

**Pull request merged**
